### PR TITLE
Implement boat model

### PR DESCRIPTION
**Pull request by ZoeTheFox**
Implemented the BOAT

# Nya :3c

### CODE REVIEW

**Review by Bergdoktor258 — APPROVED** [review]

**Review by buchidotcom — APPROVED** [review]
scho a bissl a bledsinn oba vo mir aus

**Comment by Bergdoktor258** [comment]
ggood

**Comment by buchidotcom** [comment]
ehhh

**Comment by buchidotcom** [comment]
buchi-approved

**Comment by ZoeTheFox** [comment]
meow?

**Pull request merged**
